# Generated by Django 5.2.8 on 2025-11-10 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available_quantity', models.DecimalField(decimal_places=2, help_text='In Kilograms', max_digits=8)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vegetables', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
