# Generated by Django 5.2.8 on 2025-11-11 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='vegetable',
            new_name='buyer',
        ),
    ]
